server:
  port: 8001

spring:
  application:
    name: hits-event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hits_event
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: "true"
    change-log: db/changelog/db.changelog-master.xml

jwt:
  secret: hits2025972303hits2025972303hits20259723032025hits
  lifetime: 300m